version: '3.8'
services:
  fabricstudio:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud
    stdin_open: true
    tty: true
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
